import { ReactNode } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

interface RootLayoutProps {
  children: ReactNode;
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <head>
        <meta name="google-adsense-account" content="ca-pub-6011504846169529"></meta>
        </head>
        <body>
         <nav style={{ padding: '1rem', background: '#f0f0f0' }}>
            <Link href="/">Home</Link> |{" "}
           <Link href="/about">About</Link> |{" "}
           <Link href="/contact">Contact</Link>
         </nav>
         {children}
      </body>
    </html>
  );
}

