
import { ReactNode } from 'react';
import Navbar from '../components/Navbar';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

interface RootLayoutProps {
  children: ReactNode;
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <meta name="google-adsense-account" content="ca-pub-6011504846169529"></meta>
        </head>
          <body>
          <Navbar />
            <main style={{ padding: '2rem', maxWidth: '1000px', margin: 'auto' }}>
              {children}
            </main>
          </body>
    </html>
  );
}

